// Command genmatrix generates renderer-scoped signatures from the validated
// evidence matrix. Generated code is deterministic and has no runtime XML IO.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type signature struct {
	N        string `xml:"n,attr"`
	Form     string `xml:"form,attr"`
	Scope    string `xml:"renderer,attr"`
	Verified string `xml:"verified,attr"`
	Requires string `xml:"requires,attr"`
	Cite     string `xml:"cite,attr"`
}
type scenario struct {
	ID       string `xml:"id,attr"`
	Status   string `xml:"status,attr"`
	Verified string `xml:"verified,attr"`
	Base     string `xml:"base,attr"`
	XY       string `xml:"vsfilter,attr"`
	Mod      string `xml:"vsfiltermod,attr"`
	Requires string `xml:"requires,attr"`
	Cite     string `xml:"cite,attr"`
}

type tag struct {
	Name      string     `xml:"name,attr"`
	Scenarios []scenario `xml:"scen"`
	Params    struct {
		Exhaustive     string      `xml:"exhaustive,attr"`
		ExhaustiveCite string      `xml:"exhaustive-cite,attr"`
		Signatures     []signature `xml:"sig"`
	} `xml:"params"`
}
type matrix struct {
	Tags   []tag `xml:"tag"`
	Groups []struct {
		Names string `xml:"names,attr"`
	} `xml:"taggroup"`
}

func mask(fields string) (uint8, error) {
	var out uint8
	for _, field := range strings.Fields(fields) {
		var b uint8
		switch field {
		case "libass":
			b = 1
		case "xy":
			b = 2
		case "vsm":
			b = 4
		default:
			return 0, fmt.Errorf("unknown renderer %q", field)
		}
		if out&b != 0 {
			return 0, fmt.Errorf("duplicate renderer %q", field)
		}
		out |= b
	}
	return out, nil
}

// canonicalNewlines gives a stable evidence digest across Git worktrees with
// LF, CRLF or CR physical line endings. Source-preserving fixtures are not
// involved in this normalization.
func canonicalNewlines(data []byte) []byte {
	data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
	return bytes.ReplaceAll(data, []byte("\r"), []byte("\n"))
}

// requirementMask accepts only canonical guard sets from the pinned source.
// _LUA cannot be independently enabled without _VSMOD.
func requirementMask(raw string) (uint8, error) {
	switch raw {
	case "":
		return 0, nil
	case "_VSMOD":
		return 1, nil
	case "_VSMOD _LUA":
		return 3, nil
	default:
		return 0, fmt.Errorf("unsupported signature requirements %q", raw)
	}
}

func run() error {
	check := flag.Bool("check", false, "fail if generated output is stale")
	flag.Parse()
	input := filepath.Join("..", "..", "..", "docs", "ass-tags.xml")
	data, err := os.ReadFile(input)
	if err != nil {
		return err
	}
	var m matrix
	if err = xml.Unmarshal(data, &m); err != nil {
		return err
	}
	// Group stubs are documented but unverified, with no applicable signatures.
	// Keep their names resolvable without inventing arities or source proofs.
	for _, group := range m.Groups {
		for _, name := range strings.Fields(group.Names) {
			m.Tags = append(m.Tags, tag{Name: name})
		}
	}
	sort.Slice(m.Tags, func(i, j int) bool { return m.Tags[i].Name < m.Tags[j].Name })
	sum := sha256.Sum256(canonicalNewlines(data))
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out, "package renderer")
	fmt.Fprintf(&out, "const matrixSHA256 = %q\n", fmt.Sprintf("%x", sum))
	fmt.Fprintln(&out, "var matrixTags = map[string]tagMeta{")
	seen := make(map[string]bool)
	for _, t := range m.Tags {
		if t.Name == "" || seen[t.Name] {
			return fmt.Errorf("duplicate or unnamed tag %q", t.Name)
		}
		seen[t.Name] = true
		fmt.Fprintf(&out, "%q:{scenarios: []generatedScenario{", t.Name)
		for _, s := range t.Scenarios {
			v, err := mask(s.Verified)
			if err != nil {
				return fmt.Errorf("%s/%s: %w", t.Name, s.ID, err)
			}
			if s.Status != "V" && v != 0 {
				return fmt.Errorf("%s/%s: unverified scenario declares verified scope", t.Name, s.ID)
			}
			for i, value := range []string{s.Base, s.XY, s.Mod} {
				if v&(1<<i) != 0 && (value == "" || value == "unchecked" || s.Cite == "") {
					return fmt.Errorf("%s/%s: missing verified outcome or citation", t.Name, s.ID)
				}
			}
			requires, err := requirementMask(s.Requires)
			if err != nil {
				return fmt.Errorf("%s/%s: %w", t.Name, s.ID, err)
			}
			fmt.Fprintf(&out, "{id:%q,verified:%d,outcomes:[3]string{%q,%q,%q},requires:%d,citation:%q},", s.ID, v, s.Base, s.XY, s.Mod, requires, s.Cite)
		}
		fmt.Fprint(&out, "},signatures: []generatedSignature{")
		for _, s := range t.Params.Signatures {
			n, e := strconv.Atoi(s.N)
			if e != nil || n < 0 {
				return fmt.Errorf("%s: invalid arity %q", t.Name, s.N)
			}
			sc, e := mask(s.Scope)
			if e != nil {
				return fmt.Errorf("%s: %w", t.Name, e)
			}
			v, e := mask(s.Verified)
			if e != nil {
				return fmt.Errorf("%s: %w", t.Name, e)
			}
			if sc == 0 || v & ^sc != 0 {
				return fmt.Errorf("%s: invalid signature scope", t.Name)
			}
			requires, e := requirementMask(s.Requires)
			if e != nil {
				return fmt.Errorf("%s: %w", t.Name, e)
			}
			if requires != 0 && sc != 4 {
				return fmt.Errorf("%s: build requirements apply only to VSFilterMod signatures", t.Name)
			}
			var form string
			switch s.Form {
			case "bare":
				form = "Bare"
			case "paren":
				form = "Paren"
			case "both":
				form = "Both"
			default:
				return fmt.Errorf("%s: invalid form %q", t.Name, s.Form)
			}
			fmt.Fprintf(&out, "{count:%d,form:%s,scope:%d,verified:%d,", n, form, sc, v)
			if requires != 0 {
				fmt.Fprintf(&out, "requires:%d,", requires)
			}
			fmt.Fprintf(&out, "citation:%q},", s.Cite)
		}
		complete, e := mask(t.Params.Exhaustive)
		if e != nil {
			return fmt.Errorf("%s: exhaustive signature scope: %w", t.Name, e)
		}
		if complete == 0 && t.Params.ExhaustiveCite != "" {
			return fmt.Errorf("%s: exhaustive source citation without an exhaustive scope", t.Name)
		}
		if complete != 0 {
			if t.Params.ExhaustiveCite == "" {
				return fmt.Errorf("%s: exhaustive signature scope needs independent source citation", t.Name)
			}
			for _, renderer := range []struct {
				mask uint8
				name string
			}{{1, "libass"}, {2, "xy"}, {4, "vsm"}} {
				if complete&renderer.mask == 0 {
					continue
				}
				cited := false
				for _, token := range strings.Fields(t.Params.ExhaustiveCite) {
					if strings.HasPrefix(token, renderer.name+":") {
						cited = true
					}
				}
				if !cited {
					return fmt.Errorf("%s: missing exhaustive source citation for %s", t.Name, renderer.name)
				}
				found := false
				for _, s := range t.Params.Signatures {
					sc, err := mask(s.Scope)
					if err != nil {
						return err
					}
					if sc&renderer.mask == 0 {
						continue
					}
					found = true
					verified, err := mask(s.Verified)
					if err != nil {
						return err
					}
					if verified&renderer.mask == 0 {
						return fmt.Errorf("%s: incomplete %s evidence cannot prove exhaustive arities", t.Name, renderer.name)
					}
				}
				if !found {
					return fmt.Errorf("%s: no applicable signatures for exhaustive %s scope", t.Name, renderer.name)
				}
			}
			fmt.Fprintf(&out, "}, exhaustive:%d, exhaustiveCitation:%q},\n", complete, t.Params.ExhaustiveCite)
		} else {
			fmt.Fprintln(&out, "}},")
		}
	}
	fmt.Fprintln(&out, "}")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	target := "matrix_generated.go"
	if *check {
		current, err := os.ReadFile(target)
		if err != nil {
			return err
		}
		if !bytes.Equal(canonicalNewlines(current), formatted) {
			return fmt.Errorf("%s is stale: run go generate ./internal/ass/renderer", target)
		}
		return nil
	}
	return os.WriteFile(target, formatted, 0644)
}
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
